### ISSUE TITLE
Role of Data Science in Carbon Capture

### ISSUE THREAD

**Issue by Lav-Mehta** [g4challenge/ds4ns#3]
**Author**

- **Name**: Lav Mehta

- **Affiliation**: FH Kufstein

**Keywords**
- Climate Change
- Carbon Capture
- Thermodynamics
- Data Science

Full PDF: [Abstract_CO2_Mehta.pdf](https://github.com/g4challenge/ds4ns/files/7837888/Abstract_CO2_Mehta.pdf)

**Comment by 2010837481** [comment]
[Peer Review Report_01_Mehta.pdf](https://github.com/g4challenge/ds4ns/files/7880866/Peer.Review.Report_01_Mehta.pdf)

**Comment by wintermoon2021** [comment]
[20220117_0100_Review_Lav_Paper.pdf](https://github.com/g4challenge/ds4ns/files/7885120/20220117_0100_Review_Lav_Paper.pdf)

**Comment by feedme-foodapp** [comment]
[peer_review_mehta.pdf](https://github.com/g4challenge/ds4ns/files/7889226/peer_review_mehta.pdf)
