### ISSUE TITLE
Optimize Agriculture using Artificial Intelligence

### ISSUE THREAD

**Issue by feedme-foodapp** [g4challenge/ds4ns#4]
[**Abstract**]

Agriculture plays a significant role in the growth and development 
of the economy of any nation. But the emergences of crop-related
diseases affect the productivity [1]. This has not only an impact on 
the economy itself, but also influences the security of food supply. 

Conventional methods of pest control are mostly controversial and 
no longer tolerable for the environment. To cope with these issues 
and to implement effective strategies to prevent the propagation of 
diseases, crop disease diagnosis with artificial methods is required.
Commonly used techniques are k-Means clustering, Convolutional 
Neural Network CNN, and image processing tasks. In this paper, a 
combination of Convolutional Neural Network and autoencoder is 
explained, which is referred as Convolutional Encoder Network, to 
identify crop disease using crop leaf images.

**Keywords**

Artificial Intelligence, Machine Learning, Deep Learning, Crop 
disease detection, Convolutional Encoder Network, PlantVillage

Link to PDF: [short_paper_walser.pdf](https://github.com/g4challenge/ds4ns/files/7838002/short_paper_walser.pdf)

**Comment by Vivinternational** [comment]
[Optimize Agriculture using Artificial Intelligence_Review.pdf](https://github.com/g4challenge/ds4ns/files/7896575/Optimize.Agriculture.using.Artificial.Intelligence_Review.pdf)
[short_paper_walser_review.pdf](https://github.com/g4challenge/ds4ns/files/7896586/short_paper_walser_review.pdf)

**Comment by Lav-Mehta** [comment]
[Review_Optimize Agriculture using Artificial Intelligence_Mehta.pdf](https://github.com/g4challenge/ds4ns/files/7933252/Review_Optimize.Agriculture.using.Artificial.Intelligence_Mehta.pdf)

**Comment by holzmi-stud-kufstein** [comment]
[Peer Review Report_02_walser.pdf](https://github.com/g4challenge/ds4ns/files/7936741/Peer.Review.Report_02_walser.pdf)
