### ISSUE TITLE
XAI Potential Limitations in the Medical Sector

### ISSUE THREAD

**Issue by 2010837481** [g4challenge/ds4ns#5]
Author

Name: Robert Bartz

Affiliation: FH Kufstein

Keywords:
Explainable ai, artificial, intelligence, xai, black box, limitations, risks, healthcare, pneumonia, detection, CNN

Abstract:
The black box nature of state-of-the-art machine learning algorithms almost imposed the question whether Artificial Intelligence (AI) decisions must be made transparent und humanly understandable, particularly in critical scenarios such as healthcare. This work aims to provide the audience with inspiration and starting points regarding potential limitations of XAI techniques in the context of medical decision making, especially on the local model level. The key idea is that current XAI libraries are not suitable to fully explain and justify medical diagnosis on the individual case. This is demonstrated via the example of pneumonia detection through a CCN trained on x-ray images.

Full PDF:
[Bartz_Explanability and Associated Potential Limitations in the Medical Sector_DS_for_NS.pdf](https://github.com/g4challenge/ds4ns/files/7845829/Bartz_Explanability.and.Associated.Potential.Limitations.in.the.Medical.Sector_DS_for_NS.pdf)

**Comment by holzmi-stud-kufstein** [comment]
[Uploading Peer Review Report_02_Bartz.docx…]()

**Comment by wintermoon2021** [comment]
[20220116_1418_Explainable_AI_Robert_Bartz.pdf](https://github.com/g4challenge/ds4ns/files/7885122/20220116_1418_Explainable_AI_Robert_Bartz.pdf)

**Comment by 2010837481** [comment]
Danke Euch :)

**Comment by g4challenge** [comment]
> Uploading Peer Review Report_02_Bartz.docx…

@holzmi-stud-kufstein upload not working

**Comment by 2010837481** [comment]
@holzmi-stud-kufstein kannst Du nochmal hochladen? Dein  REview ist nicht durchgegangen. merci!

**Comment by holzmi-stud-kufstein** [comment]
[Uploading Peer Review Report_02_Bartz.pdf…]()

**Comment by holzmi-stud-kufstein** [comment]
[Peer Review Report_02_Bartz.pdf](https://github.com/g4challenge/ds4ns/files/7956859/Peer.Review.Report_02_Bartz.pdf)
