### ISSUE TITLE
Could machine learning help us to solve the climate crisis?

### ISSUE THREAD

**Issue by holzmi-stud-kufstein** [g4challenge/ds4ns#6]
**Author**

- **Name**: Michael Holzinger

- **Affiliation**: FH Kufstein

**Keywords**
Climate change, machine learning, greenhouse gases, climate crises, reduce greenhouse gases

**Abstract**
The Climate Crisis is a real problem in different aspects with a significant impact on our life. Machine learning is a powerful tool to solve problems or identify solutions and answers for many issues. Now is the question of how we can Machine learning use that we have a beneficial impact to solve the climate crisis.
..

Full PDF: 
[Could machine learning help us to solve the climate crisis.pdf](https://github.com/g4challenge/ds4ns/files/7866112/Could.machine.learning.help.us.to.solve.the.climate.crisis.pdf)

**Comment by 2010837481** [comment]
[Peer Review Report_01_Holzinger.docx](https://github.com/g4challenge/ds4ns/files/7880862/Peer.Review.Report_01_Holzinger.docx)

**Comment by wintermoon2021** [comment]
[20220115_1730_Machine_Learning_Climate_Crisis_Review_Paper.pdf](https://github.com/g4challenge/ds4ns/files/7885124/20220115_1730_Machine_Learning_Climate_Crisis_Review_Paper.pdf)

**Comment by feedme-foodapp** [comment]
[Uploading peer_review_holzinger.pdf…]()

**Comment by g4challenge** [comment]
> Uploading peer_review_holzinger.pdf…

upload not working @feedMe-foodapp
